### ISSUE TITLE
Website structure for Asia

### ISSUE THREAD

**Issue by KallieFerguson** [qiskit-community/community.qiskit.org#32]
Please make an Asia website that we can push content edits to in the same spot where Europe is located. This language can be added:

What is Qiskit Camp?

Qiskit Camps are an immersive experience that consists of training sessions, deep technical talks, and a hackathon alongside the Qiskit core development team. At Qiskit Camp, attendees can collaborate with both quantum researchers and computer scientists to connect with the larger global quantum community.

2019 Qiskit Camp Asia will be hosted near Tokyo, Japan in December. Invitations will be distributed prior to the event.

Location

Qiskit Camp Asia will take place at Hoshino Resorts Risonare Yatsugatake (https://risonare.com/yatsugatake/en/) in Japan

129-1 Kobuchisawachō, Hokuto-shi, Yamanashi-ken 408-0044, Japan

Agenda

Leave blank for now and we'll update through pull request for content.

**Comment by delapuente** [comment]
Closed by #33
