### ISSUE TITLE
Where did Qiskit Camp pages go?

### ISSUE THREAD

**Issue by KallieFerguson** [qiskit-community/community.qiskit.org#41]
Hi team,

I noticed we no longer have a place for editing content on the Qiskit Camp Africa and Asia pages. Can we bring them back? Or do you all hate my pull requests? 

THX.

Kallie

**Comment by SooluThomas** [comment]
Hi Kalli,

As per [this PR](https://github.com/qiskit-community/community.qiskit.org/pull/39), we renamed the `src` to `content`. So you can find all the content [here](https://github.com/qiskit-community/community.qiskit.org/tree/master/content).

On behalf on my team, I apologize for not bringing that to your notice. Also please note to checkout recent commits to know about the changes.
<img width="986" alt="Screen Shot 2019-07-31 at 12 34 08 PM" src="https://user-images.githubusercontent.com/11485594/62230717-686ac100-b390-11e9-8008-ce0ba06bdede.png">

Thanks.

**Comment by KallieFerguson** [comment]
Thank you, Soolu!

**Comment by SooluThomas** [comment]
> Thank you, Soolu!

You're always welcomed to open new issues. It will only help us grow together as a team :)
