### ISSUE TITLE
Shortening Event Website links

### ISSUE THREAD

**Issue by KallieFerguson** [qiskit-community/community.qiskit.org#42]
Can we make https://community.qiskit.org/events/africa/ --> qiskit.camp/africa

and

https://community.qiskit.org/events/asia/ --> qiskit.camp/asia

**Comment by delapuente** [comment]
We can provider shorteners for those, yes.

**Comment by delapuente** [comment]
Closed by https://github.com/qiskit-community/qiskit.camp/commit/7b4ac5fdfc3c4b0b135702335d610937472e8783
