### ISSUE TITLE
redirect textbook from qiskit.org/textbook to community.qiskit.org/textbook

### ISSUE THREAD

**Issue by aasfaw** [qiskit-community/community.qiskit.org#81]
In the same way that qiskit.org/education redirects to community.qiskit.org/education, qiskit.org/textbook should lead to community.qiskit.org/textbook.

**Comment by 1ucian0** [comment]
This issue belongs to qiskit.org. Forwarded to https://github.com/Qiskit/qiskit.org/issues/219
